name: TOOLME2

on:
  workflow_dispatch:

jobs:
  part1:
    name: Part 1
    runs-on: windows-latest
    timeout-minutes: 360  # ใช้เวลาไม่เกิน 6 ชั่วโมง (360 นาที)
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/starredntgod1/redno/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

  part2:
    name: Part 2
    runs-on: windows-latest
    needs: part1  # รอให้ part1 เสร็จ
    timeout-minutes: 360  # ใช้เวลาไม่เกิน 6 ชั่วโมง (360 นาที)
    
    steps:
      - name: Show Website
        run: cmd /c show.bat

  part3:
    name: Part 3
    runs-on: windows-latest
    needs: part2  # รอให้ part2 เสร็จ
    timeout-minutes: 360  # ใช้เวลาไม่เกิน 6 ชั่วโมง (360 นาที)
    
    steps:
      - name: Time Counter
        run: cmd /c loop.bat
