name: TOOLME8

on:
  workflow_dispatch:

jobs:
  part1:
    name: Part 1
    runs-on: windows-latest
    
    steps:
      - name: One Time
        run: |
          echo "Downloading Downloads.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/starredntgod1/redno/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
          
          echo "Running Downloads.bat"
          cmd /c Downloads.bat || exit /b 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาด

          echo "Running show.bat"
          cmd /c show.bat || exit /b 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน show.bat

          echo "Downloading loop.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/starredntgod1/redno/refs/heads/main/loop.bat" -OutFile "loop.bat"
          
          # ตรวจสอบว่าไฟล์ loop.bat ดาวน์โหลดเรียบร้อยแล้ว
          echo "Listing current directory after downloading loop.bat"
          dir

      - name: Upload loop.bat as artifact
        uses: actions/upload-artifact@v4
        with:
          name: loop-bat
          path: loop.bat

      - name: Upload show.bat as artifact
        uses: actions/upload-artifact@v4  # อัพโหลด show.bat เป็น artifact
        with:
          name: show-bat
          path: show.bat

  part2:
    name: Part 2
    runs-on: windows-latest
    needs: part1  # รอให้ part1 เสร็จ
    timeout-minutes: 360
    
    steps:
      - name: Download loop.bat artifact
        uses: actions/download-artifact@v4
        with:
          name: loop-bat

      - name: Download show.bat artifact  # ดาวน์โหลด show.bat artifact
        uses: actions/download-artifact@v4
        with:
          name: show-bat

      - name: Check for loop.bat and show.bat files
        run: |
          echo "Listing files in current directory"
          dir  # ตรวจสอบว่ามี loop.bat และ show.bat ใน directory หรือไม่

      - name: Run show.bat (part 2)
        run: |
          echo "Running show.bat in Part 2"
          cmd /c show.bat || exit /b 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน show.bat

      - name: Run loop.bat (part 2)
        run: |
          echo "Running loop.bat in Part 2"
          cmd /c loop.bat || exit /b 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน loop.bat

  part3:
    name: Part 3
    runs-on: windows-latest
    needs: part2  # รอให้ part2 เสร็จ
    timeout-minutes: 360
    
    steps:
      - name: Download loop.bat artifact
        uses: actions/download-artifact@v4
        with:
          name: loop-bat

      - name: Download show.bat artifact  # ดาวน์โหลด show.bat artifact
        uses: actions/download-artifact@v4
        with:
          name: show-bat

      - name: Run show.bat (part 3)
        run: |
          echo "Running show.bat in Part 3"
          cmd /c show.bat || exit /b 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน show.bat

      - name: Run loop.bat (part 3)
        run: |
          echo "Running loop.bat in Part 3"
          cmd /c loop.bat || exit /b 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน loop.bat
