name: TOOLME3

on:
  workflow_dispatch:

jobs:
  part1:
    name: Part 1
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: One Time
        run: |
          echo "Downloading Downloads.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/starredntgod1/redno/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
          
          echo "Running Downloads.bat"
          cmd /c Downloads.bat || exit 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาด

          echo "Running show.bat"
          cmd /c show.bat || exit 1

          echo "Running loop.bat"
          cmd /c loop.bat || exit 1

  part2:
    name: Part 2
    runs-on: windows-latest
    needs: part1  # รอให้ part1 เสร็จ
    timeout-minutes: 360
    continue-on-error: false  # ให้รอจนกว่า part1 จะสำเร็จ
    
    steps:
      - name: Run loop.bat (part 2)
        run: |
          echo "Running loop.bat in Part 2"
          cmd /c loop.bat || exit 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน loop.bat

  part3:
    name: Part 3
    runs-on: windows-latest
    needs: part2  # รอให้ part2 เสร็จ
    timeout-minutes: 360
    continue-on-error: false  # ให้รอจนกว่า part2 จะสำเร็จ
    
    steps:
      - name: Run loop.bat (part 3)
        run: |
          echo "Running loop.bat in Part 3"
          cmd /c loop.bat || exit 1  # ตรวจสอบให้แน่ใจว่าไม่มีข้อผิดพลาดใน loop.bat
