name: TOOLME35

on:
  workflow_dispatch:

jobs:
  part1:
    name: Part 1
    runs-on: windows-latest
    
    steps:
      - name: Download Downloads.bat
        run: |
          echo "Downloading Downloads.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/starredntgod1/redno/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"

      - name: Run Downloads.bat
        run: |
          echo "Running Downloads.bat"
          cmd /c Downloads.bat  # รัน Downloads.bat โดยไม่บันทึกผลลัพธ์

      - name: Run show.bat
        run: |
          echo "Running show.bat in Part 1"
          cmd /c show.bat  # รัน show.bat โดยไม่บันทึกผลลัพธ์

      - name: Download loop.bat
        run: |
          echo "Downloading loop.bat"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/starredntgod1/redno/refs/heads/main/loop.bat" -OutFile "loop.bat"
        
      - name: Upload important files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: important-files  # ตั้งชื่อ artifact ที่จะอัพโหลด
          path: |  # ระบุไฟล์ที่ต้องการอัพโหลด
            Downloads.bat
            show.bat
            loop.bat

  part2:
    name: Part 2
    runs-on: windows-latest
    needs: part1  # รอให้ part1 เสร็จ
    
    steps:
      - name: Download important files from artifact
        uses: actions/download-artifact@v4
        with:
          name: important-files  # ดาวน์โหลด artifact ที่อัพโหลดจาก part1

      - name: Check files after download
        run: |
          echo "Listing files in current directory"
          dir  # ตรวจสอบว่ามีไฟล์ที่ต้องการใน directory หรือไม่

      - name: Run Downloads.bat in Part 2
        run: |
          echo "Running Downloads.bat in Part 2"
          cmd /c Downloads.bat  # รัน Downloads.bat ใน part2

      - name: Run show.bat in Part 2
        run: |
          echo "Running show.bat in Part 2"
          cmd /c show.bat  # รัน show.bat ใน part2

      - name: Run loop.bat in Part 2
        run: |
          echo "Running loop.bat in Part 2"
          cmd /c loop.bat  # รัน loop.bat ใน part2

  part3:
    name: Part 3
    runs-on: windows-latest
    needs: part2  # รอให้ part2 เสร็จ
    
    steps:
      - name: Download important files from artifact
        uses: actions/download-artifact@v4
        with:
          name: important-files  # ดาวน์โหลด artifact ที่อัพโหลดจาก part1

      - name: Check files after download
        run: |
          echo "Listing files in current directory"
          dir  # ตรวจสอบว่ามีไฟล์ที่ต้องการใน directory หรือไม่

      - name: Run Downloads.bat in Part 3
        run: |
          echo "Running Downloads.bat in Part 3"
          cmd /c Downloads.bat  # รัน Downloads.bat ใน part3

      - name: Run show.bat in Part 3
        run: |
          echo "Running show.bat in Part 3"
          cmd /c show.bat  # รัน show.bat ใน part3

      - name: Run loop.bat in Part 3
        run: |
          echo "Running loop.bat in Part 3"
          cmd /c loop.bat  # รัน loop.bat ใน part3
